version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chopnow_db
    restart: always
    environment:
      POSTGRES_USER: chopnow_user
      POSTGRES_PASSWORD: Chopnow_API
      POSTGRES_DB: chopnow_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: